import type { GuardTactic, Mission, Solid, Vec } from '../sim/types';

const wall = (id: string, x: number, y: number, w: number, h: number, floor = 0): Solid => ({
  id,
  x,
  y,
  w,
  h,
  height: 2.2,
  kind: 'wall',
  ...(floor ? { floor } : {}),
});
const post = (
  x: number,
  y: number,
  angle: number,
  role?: GuardTactic['role'],
  floor = 0,
  patrol?: Vec[],
) => {
  const p = { x, y, ...(floor ? { floor } : {}) };
  return {
    position: p,
    patrol: patrol ?? [p],
    angle,
    ...(role ? { tactic: { role, posts: patrol ?? [p] } } : {}),
  };
};
const upper = (x: number, y: number): Vec => ({ x, y, floor: 1 });

export const continuity: Mission = {
  id: 'continuity',
  number: '13',
  title: 'Continuity',
  location: 'Continuity House / executive control · 13:20',
  objective: 'capture',
  daylight: true,
  trackingCamera: true,
  flashGrenades: true,
  loadout: ['pistol', 'pistol', 'automatic', 'coil'],
  continuity: { cycle: 12 },
  building: {
    footprint: { x: 22, y: 8, w: 28.4, h: 22.4 },
    upper: { x: 22.4, y: 8.4, w: 27.6, h: 21.6 },
    stairs: [{ x: 26, y: 12 }, upper(26, 12)],
  },
  evidenceName: 'Continuity register',
  relayTime: 5,
  escort: {
    id: 'kestrel',
    name: 'Ada Kestrel',
    hp: 90,
    speed: 2.5,
    locked: false,
    vulnerable: false,
  },
  description: 'Remove Ada Kestrel from the company’s chain of command.',
  intro:
    'Mara: Kestrel is upstairs at Continuity House. Bring her out in handcuffs, or end her command there. Either way, bring the crew home. Use UP and DOWN to change floors.',
  briefing: {
    lead: 'Kestrel has stopped delegating.',
    body: 'Reach the upper control room. To arrest Kestrel, isolate both ground-floor feeds and apply handcuffs at CUFF. Otherwise attack her directly. Bring every survivor—and Kestrel if arrested—to VAN.',
    routes: [
      {
        title: 'Two floors',
        body: 'UP and DOWN move the selected operatives through the stairwell. The view follows the active operative’s floor. Select a crew portrait to switch back to a split teammate. Kestrel follows her escort down the stairs; a waiting prisoner stays where you left her. Bullets, sight and flashes cannot cross the ceiling.',
      },
      {
        title: 'Remove her control',
        body: 'Kestrel alternates WEST and EAST turret power every twelve seconds. Cables and the control display show the active feed. Both breakers are downstairs; isolated feeds cannot be restored. Shut both down to make her surrender. CUFF takes three seconds with free hands. Guards will oppose the arresting operative; they will not shoot their director.',
      },
      {
        title: 'Service access',
        body: 'KIT is outside the west staff entrance. INSPECT in reception gives a disguised pistol carrier twenty-four seconds with both turret circuits stopped. Tampering outside inspection is conspicuous. Upstairs, a credential officer patrols the west gallery; avoid prolonged close contact. RADIO is at the far end of the upper floor, beyond security.',
      },
      {
        title: 'Direct action',
        body: 'Attack Kestrel’s body to issue a deliberate lethal order; CUFF is the nonlethal interaction above her. She has ordinary health and stays in the screened control room. RADIO stops response teams but does not stop her wired defenses. Killing her stops their local controller. REGISTER is optional on either route.',
      },
    ],
  },
  width: 60,
  height: 42,
  restricted: { x: 17, y: 4, w: 38, h: 31 },
  secure: { x: 38, y: 18, w: 12, h: 12, floor: 1 },
  gate: { x: 55, y: 29, w: 0.35, h: 4 },
  gateOutside: { x: 56.5, y: 31 },
  gateInsideOnly: true,
  perimeterExtraction: true,
  response: {
    spawns: [
      { x: 57, y: 30 },
      { x: 57, y: 31 },
      { x: 57, y: 32 },
    ],
    patrol: [
      { x: 53, y: 31 },
      { x: 33, y: 33 },
      { x: 33, y: 26 },
    ],
  },
  security: {
    inspectionTime: 24,
    turrets: [
      {
        position: { x: 34, y: 24 },
        angle: Math.PI / 2,
        circuit: 'power-west',
        cable: [
          { x: 26, y: 24 },
          { x: 34, y: 24 },
        ],
      },
      {
        position: { x: 46, y: 17 },
        angle: Math.PI,
        circuit: 'power-east',
        cable: [
          { x: 46, y: 25 },
          { x: 46, y: 17 },
        ],
      },
      {
        position: upper(34, 12),
        angle: Math.PI / 2,
        circuit: 'power-west',
        cable: [upper(26, 24), upper(34, 24), upper(34, 12)],
      },
      {
        position: upper(43, 27),
        angle: -Math.PI / 2,
        circuit: 'power-east',
        cable: [upper(46, 25), upper(43, 25), upper(43, 27)],
      },
    ],
  },
  solids: [
    wall('fence-north', 17, 4, 38.35, 0.35),
    wall('fence-east', 55, 4, 0.35, 25),
    wall('fence-south', 17, 35, 38.35, 0.35),
    wall('fence-east-foot', 55, 33, 0.35, 2.35),
    wall('fence-west-top', 17, 4, 0.35, 17),
    wall('fence-west-foot', 17, 27, 0.35, 8.35),
    wall('house-north', 22, 8, 28.4, 0.4),
    wall('house-east', 50, 8, 0.4, 22.4),
    wall('house-west-top', 22, 8, 0.4, 14),
    wall('house-west-foot', 22, 26, 0.4, 4.4),
    wall('house-south-west', 22, 30, 7, 0.4),
    wall('house-south-east', 34, 30, 16.4, 0.4),
    wall('ground-divider-top', 37, 8.4, 0.4, 11.6),
    wall('ground-divider-foot', 37, 24, 0.4, 6),
    { id: 'reception', x: 28, y: 25, w: 3, h: 0.8, height: 1.1, kind: 'shelves' },
    { id: 'ground-rack', x: 40, y: 16, w: 5, h: 0.8, height: 1.8, kind: 'server' },
    { id: 'west-feed', x: 24, y: 24, w: 0.7, h: 2, height: 1.4, kind: 'server' },
    { id: 'east-feed', x: 48, y: 24, w: 0.7, h: 2, height: 1.4, kind: 'server' },
    { id: 'stair-screen', x: 28, y: 15, w: 4, h: 0.6, height: 1.5, kind: 'shelves' },
    wall('upper-north', 22, 8, 28.4, 0.4, 1),
    wall('upper-east', 50, 8, 0.4, 22.4, 1),
    wall('upper-west', 22, 8, 0.4, 22.4, 1),
    wall('upper-south', 22, 30, 28.4, 0.4, 1),
    wall('upper-divider-top', 37, 8.4, 0.4, 8, 1),
    wall('upper-divider-foot', 37, 21, 0.4, 4, 1),
    wall('upper-divider-toe', 37, 28.5, 0.4, 1.5, 1),
    wall('control-screen', 40, 21, 6, 0.4, 1),
    {
      id: 'upper-stair-screen',
      x: 28,
      y: 15,
      w: 4,
      h: 0.6,
      height: 1.5,
      kind: 'shelves',
      floor: 1,
    },
    { id: 'upper-cover', x: 29, y: 24, w: 3, h: 1, height: 1.3, kind: 'shelves', floor: 1 },
    { id: 'control-desk', x: 44, y: 25, w: 4, h: 0.8, height: 1.1, kind: 'server', floor: 1 },
    { id: 'upper-radio', x: 47, y: 10, w: 1.6, h: 0.8, height: 1.4, kind: 'server', floor: 1 },
    { id: 'yard-screen', x: 39, y: 32, w: 5, h: 1, height: 1.3, kind: 'crate' },
    { id: 'street-workshop', x: 5, y: 9, w: 6, h: 10, height: 2.8, kind: 'building' },
    { id: 'van', x: 10, y: 34, w: 1.6, h: 3, height: 1.55, kind: 'van' },
  ],
  landmarks: [
    {
      id: 'disguise',
      tag: 'KIT',
      x: 14,
      y: 28,
      label: 'Service engineer identity',
      detail: 'One disguise, for a pistol carrier. Inspector checks still apply upstairs.',
    },
    {
      id: 'authorise',
      tag: 'INSPECT',
      x: 29.5,
      y: 27,
      label: 'Maintenance inspection',
      detail: 'In disguise, suspend the wired defenses for 24 seconds. One use.',
    },
    {
      id: 'power-west',
      tag: 'WEST',
      x: 26,
      y: 24,
      label: 'West feed isolation',
      detail: 'Four seconds. Irreversible isolation; removes one of Kestrel’s controls.',
    },
    {
      id: 'power-east',
      tag: 'EAST',
      x: 46,
      y: 25,
      label: 'East feed isolation',
      detail: 'Four seconds. Both feeds must be isolated for a peaceful arrest.',
    },
    {
      id: 'stairs-up',
      tag: 'UP',
      x: 26,
      y: 12,
      label: 'Stairs to upper floor',
      detail:
        'Click to send the selected ground-floor operatives upstairs. Orders and camera stay with the active operative.',
    },
    {
      id: 'stairs-down',
      tag: 'DOWN',
      ...upper(26, 12),
      label: 'Stairs to ground floor',
      detail:
        'Click to send selected upstairs operatives down. A following prisoner uses the stairs too.',
    },
    {
      id: 'escort',
      tag: 'CUFF',
      ...upper(46, 23),
      label: 'Arrest Ada Kestrel',
      detail:
        'Isolate WEST and EAST downstairs. Three seconds here puts Kestrel in handcuffs. Her body is a separate lethal attack target.',
    },
    {
      id: 'relay',
      tag: 'RADIO',
      ...upper(46, 12),
      label: 'Executive security relay',
      detail: 'Five seconds. Stops reinforcement calls; independent wired defenses remain.',
    },
    {
      id: 'evidence',
      tag: 'REGISTER',
      ...upper(40, 27),
      label: 'Continuity register',
      detail:
        'Optional record of the control network. Both hands occupied; set it down to arrest Kestrel.',
    },
    {
      id: 'gate',
      tag: 'GATE',
      x: 53.5,
      y: 31,
      label: 'East service gate',
      detail: 'Opens from inside.',
    },
    {
      id: 'extract',
      tag: 'VAN',
      x: 13,
      y: 35,
      label: 'Continuity House extraction',
      detail:
        'Remove Kestrel, bring every survivor to VAN, and bring Kestrel too if you arrested her.',
    },
  ],
  spawns: [
    { x: 13, y: 36 },
    { x: 14, y: 36 },
    { x: 13, y: 37 },
    { x: 14, y: 37 },
  ],
  guards: [
    post(32, 33, Math.PI, 'shield'),
    post(45, 32, Math.PI, 'support'),
    post(31, 20, 0, undefined, 0, [
      { x: 31, y: 20 },
      { x: 34, y: 20 },
    ]),
    post(46, 21, -Math.PI / 2, 'sentry'),
    post(33, 19, Math.PI / 2, 'inspector', 1, [upper(33, 19), upper(33, 27)]),
    post(42, 16, Math.PI, 'shield', 1),
    post(48, 19, -Math.PI / 2, 'sentry', 1),
    post(46, 14, Math.PI, 'support', 1),
  ],
};
